### ISSUE TITLE
Create yum repo with Reprepro

### ISSUE THREAD

**Issue by upccup** [Silvenga/examples#1]
Hi!   I'm sorry to bother you. I have read this article  https://www.digitalocean.com/community/tutorials/how-to-use-reprepro-for-a-secure-package-repository-on-ubuntu-14-04 about create an apt repo with Reprepro in ubuntu. Is very usefull for me. Is there has some experience with create a yum repo in the sam repositories . Thx again.

**Comment by Silvenga** [comment]
No bother. At this time I don't have any experience with creating yum repositories (I lean mostly to the side of Debian/Ubuntu). Sorry. :(

**Comment by upccup** [comment]
thinks for reply :+1:  i have got solution  thx
